### ISSUE TITLE
Deprecated Alacritty URL config

### ISSUE THREAD

**Issue by krmbzds** [romkatv/dotfiles-public#12]
Hi @romkatv,

I updated Alacritty today and got this deprecation message: https://github.com/alacritty/alacritty/issues/5035

I removed the URL section in my configuration file and replaced it with the following:

```yaml
hints:
  enabled:
   - regex: "(mailto:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: Control
```

I believe this serves equivalent functionality to your existing configuration.

I removed `gopher:|gemini:` protocols from the default config since I have no use for them.

I thought you might find this useful.
